# Site settings
title: "Alan Klug Photography"
email: "team@variantstudios.com"
description: "Alan Klug - photographer of Greece, Mexico, England, France and the US - photographs of Europe."
baseurl: "" # the subpath of your site, e.g. /photos/
url: "https://www.alanklugphotography.com" # the base hostname & protocol for your site
#timezone: America/Denver - Don't set for CloudCannon...for reasons.
version: "3.2.1" # the version of jekyll

#CloudCannon defaults
uploads_dir: "assets/images"

# Cloudinary
cloudinaryintro: 'https://res.cloudinary.com/www-alanklugphotography-com/image/fetch'
cloudinaryLG: '640'
cloudinarySM: '320'

# Gems for plugins
gems:
  - jekyll-paginate # Needed to add paginate on Jekyll ver 3+
  - jekyll-sitemap # Simple jekyll plugin that creates a sitemap.xml file and you can exclude files by adding 'sitemap:false' to the frontmatter of any file(s).

# Permalinks
permalink: pretty

# Pagination
paginate: 10
paginate_path: '/:num/'


#Collections
collections:
  usa:
    output: true
    permalink: '/usa/:title/'
  mexico:
    output: true
    permalink: '/mexico/:title/'
  greece:
    output: true
    permalink: '/greece/:title/'
  italy-slovenia:
    output: true
    permalink: '/italy-slovenia/:title/'
  france:
    output: true
    permalink: '/france/:title/'
  england:
    output: true
    permalink: '/england/:title/'
  brown-tones-foreign:
    output: true
    permalink: '/brown-tones-foreign/:title/'
  brown-tones-domestic:
    output: true
    permalink: '/brown-tones-domestic/:title/'

defaults:
  -
    scope:
      type: usa
    values:
      layout: photo
      title:
      id_number:
      image_path:
      description:
    scope:
      type: mexico
    values:
      layout: photo
      title:
      id_number:
      image_path:
      description:
    scope:
      type: greece
    values:
      layout: photo
      title:
      id_number:
      image_path:
      description:
    scope:
      type: italy-slovenia
    values:
      layout: photo
      title:
      id_number:
      image_path:
      description:
    scope:
      type: france
    values:
      layout: photo
      title:
      id_number:
      image_path:
      description:
    scope:
      type: england
    values:
      layout: photo
      title:
      id_number:
      image_path:
      description:
    scope:
      type: brown-tones-foreign
    values:
      layout: photo
      title:
      id_number:
      image_path:
      description:
    scope:
      type: brown-tones-domestic
    values:
      layout: photo
      title:
      id_number:
      image_path:
      description:
# typekit - Because we all need nice type faces.
typekit: 'oty8wpk'

# Google Analytics - What site isn't using it?!
google_analytics_tracking_id: 'UA-80029-47' #new: UA-80029-47 - old: UA-34283494-1

#Snipcart's Public Key
snipcart-key: 'YzIxZGU4YjMtZDI4Zi00N2FkLWFiODgtOTU3N2VkNWM2ODcxNjM2MjA3OTQ5NjY3ODUwNjM2'

exclude: ["vendor","node_modules","package.json","Gemfile","gulpfile.js","*.scss"]
