# Site settings
title: "Alan Klug Photography"
email: "team@variantstudios.com"
description: "Alan Klug - photographer of Greece, Mexico, England, France and the US - photographys of Europe."
baseurl: "" # the subpath of your site, e.g. /photos/
url: "" # the base hostname & protocol for your site
#timezone: America/Denver - Don't set for CloudCannon...for reasons.
version: "3.2.1" # the version of jekyll
author.name: "Variant Studios"
author.email: "team@variantstudios.com"

#CloudCannon defaults
uploads_dir: "assets/images"

# Gems for plugins
gems:

  - jekyll-paginate # Needed to add paginate on Jekyll ver 3+
  - jekyll-paginate-category
  - jekyll-sitemap # Simple jekyll plugin that creates a sitemap.xml file and you can exclude files by adding 'sitemap:false' to the frontmatter of any file(s).

# Permalinks
permalink: pretty

# Pagination
paginate: 10
paginate_path: '/photos/:num/'


#Collections
collections:
  usa:
    output: true
    permalink: '/usa/:title/'
  mexico:
    output: true
    permalink: '/mexico/:title/'

defaults:
  -
    scope:
      type: usa
    values:
      layout: photo
      title:
      id_number:
      image_path:
      description:
      order_number: 0
    scope:
      type: mexico
    values:
      layout: photo
      title:
      id_number:
      image_path:
      description:
      order_number: 0
# typekit - Because we all need nice type faces.
typekit: 'oty8wpk'

# Google Analytics - What site isn't using it?!
google_analytics_tracking_id: #new: UA-80029-47 - old: UA-34283494-1

#Snipcart's Public Key
snipcart-key: 'NWQ5M2M0YjAtMzAxNi00MTRhLTk1ZTgtNzA2YjEwNTJmMzFiNjM2MjA3OTQ5NjY3ODUwNjM2'

exclude: ["vendor","node_modules","package.json","Gemfile","gulpfile.js","*.scss"]
