# Site settings
title: "Alan Klug Photography"
email: "team@variantstudios.com"
description: "Alan Klug - photographer of Greece, Mexico, England, France and the US - photographys of Europe."
baseurl: "" # the subpath of your site, e.g. /photos/
url: "" # the base hostname & protocol for your site
#timezone: America/Denver - Don't set for CloudCannon...for reasons.
version: "3.2.1" # the version of jekyll
author.name: "Variant Studios"
author.email: "team@variantstudios.com"

# Gems for plugins
gems:

  - jekyll-paginate # Needed to add paginate on Jekyll ver 3+
  - jekyll-paginate-category
  - jekyll-sitemap # Simple jekyll plugin that creates a sitemap.xml file and you can exclude files by adding 'sitemap:false' to the frontmatter of any file(s).

# Permalinks
permalink: pretty

# Pagination
paginate: 10
paginate_path: '/photos/:num/'
category_dir: "categories"
category_layout: "photo.html"


#Collections
collections:
  photos:
    output: true
    permalink: '/photos/:title/'
  people:
    output: false
  categories:
    output: true
    permalink: '/photos/:title/'
  tags:
    output: true
    permalink: '/photos/:title/'

defaults:
  -
    scope:
      type: photos
    values:
      layout: photos
      title:
      image_path:
      description:
      author:
      category:
      tags:

# typekit - Because we all need nice type faces.
typekit: 'oty8wpk'

# Google Analytics - What site isn't using it?!
google_analytics_tracking_id: #UA-34283494-1

exclude: ["vendor","node_modules","package.json","Gemfile","gulpfile.js","*.scss"]
